Refactored applyToSilo and subscribe, also Added pushToSubscribers and removeFromSubscribersAtIndex to siloNode.js
radonjs/Radon pull request #34
Opened 2018-09-26 18:29 UTC by Joshua-Wright76

2018-09-26 18:34 UTC, G0ldenSp00n-zz approved these changes

2018-09-26 18:37 UTC, G0ldenSp00n-zz requested changes

2018-09-26 18:37 UTC, G0ldenSp00n commented on combineNodes.js
> +    if(head instanceof SiloNode){
Fix this with 
```javascript
head.constructor.name === 'SiloNode'
```

2018-09-26 18:44 UTC, ntsmitty approved these changes

2018-09-26 18:45 UTC, ntsmitty approved these changes

2018-09-26 21:32 UTC, G0ldenSp00n-zz approved these changes

2018-09-27 16:10 UTC, hlmitchell approved these changes

2018-09-27 16:10 UTC, merged